import {FormEvent, ReactNode, useCallback, useEffect, useState} from 'react';
import {Activity, AppWindow, ArrowRight, Boxes, Check, ChevronRight, CircleAlert, Copy, DoorOpen, KeyRound, KeySquare, KeySquare as BadgeKey, Menu, Plus, RefreshCw, Route, Server, ShieldCheck, Trash2, X} from 'lucide-react';
import {api, Application, Audit, clearAuth, Credential, Env, Grant, hasAuth, Provider, setAuth} from './api';

type View='overview'|'applications'|'providers'|'credentials'|'grants'|'audit';
const nav:[View,string,typeof Activity][]=[['overview','Overview',Activity],['applications','Applications',AppWindow],['providers','Providers',Server],['credentials','Credentials',KeySquare],['grants','Access grants',Route],['audit','Audit log',ShieldCheck]];

export default function App(){
  const [authenticated,setAuthenticated]=useState(hasAuth());
  if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>;
  return <Console onLogout={()=>{clearAuth();setAuthenticated(false)}}/>;
}

function Login({onLogin}:{onLogin:()=>void}){
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);setAuth(String(fd.get('username')),String(fd.get('password')));try{await api<Application[]>('/applications');onLogin()}catch{clearAuth();setError('The username or password was not accepted.')}finally{setBusy(false)}}
  return <main className="min-h-screen flex bg-[var(--surface)]">
    <section className="hidden lg:flex lg:w-[44%] bg-[var(--ink)] text-white p-12 flex-col justify-between">
      <Brand inverse/>
      <div className="max-w-md"><ShieldCheck size={38} strokeWidth={1.5} className="text-[oklch(0.78_0.1_294)] mb-7"/><h1 className="text-4xl font-semibold tracking-[-.03em] leading-tight text-balance">Credentials stay behind the gateway.</h1><p className="mt-5 text-[oklch(0.78_0.02_294)] leading-7 max-w-[52ch]">Manage the explicit relationships between applications, providers, credentials, and allowed routes.</p></div>
      <p className="text-xs text-[oklch(0.68_0.025_294)]">Janus control plane · Administrative access</p>
    </section>
    <section className="flex-1 flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm" aria-label="Administrator sign in"><div className="lg:hidden mb-12"><Brand/></div><p className="text-sm font-semibold text-[var(--primary)]">Secure administration</p><h2 className="text-3xl font-semibold tracking-[-.025em] mt-2">Sign in to Janus</h2><p className="text-sm text-[var(--muted)] mt-3 leading-6">Use the administrator credentials configured on this deployment.</p>
      <div className="mt-8 space-y-5"><label><span className="label">Username</span><input className="field" name="username" autoComplete="username" required autoFocus/></label><label><span className="label">Password</span><input className="field" name="password" type="password" autoComplete="current-password" required/></label></div>
      {error&&<div role="alert" className="mt-5 flex gap-2 text-sm text-[var(--danger)] bg-[oklch(0.96_0.02_25)] p-3 rounded-lg"><CircleAlert size={18}/>{error}</div>}
      <button className="btn btn-primary w-full mt-6" disabled={busy}>{busy?<><RefreshCw size={16} className="animate-spin"/>Signing in</>:<>Continue<ArrowRight size={16}/></>}</button></form></section>
  </main>
}

function Console({onLogout}:{onLogout:()=>void}){
  const [view,setView]=useState<View>('overview');const [mobile,setMobile]=useState(false);const [env,setEnv]=useState<Env|'ALL'>('ALL');
  const [apps,setApps]=useState<Application[]>([]),[providers,setProviders]=useState<Provider[]>([]),[credentials,setCredentials]=useState<Credential[]>([]),[grants,setGrants]=useState<Grant[]>([]),[audits,setAudits]=useState<Audit[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,p,c,g,e]=await Promise.all([api<Application[]>('/applications'),api<Provider[]>('/providers'),api<Credential[]>('/credentials'),api<Grant[]>('/grants'),api<{content:Audit[]}>('/audit-events?size=100')]);setApps(a);setProviders(p);setCredentials(c);setGrants(g);setAudits(e.content)}catch(e){if((e as Error).message==='AUTH_REQUIRED')onLogout();else setError((e as Error).message)}finally{setLoading(false)}},[onLogout]);
  useEffect(()=>{void load()},[load]);
  const filter=<T extends {environment?:Env}>(rows:T[])=>env==='ALL'?rows:rows.filter(x=>x.environment===env);
  return <div className="min-h-screen flex bg-[var(--surface)]">
    <aside className={`${mobile?'flex':'hidden'} fixed inset-0 z-30 lg:static lg:flex w-[258px] bg-[var(--ink)] text-white flex-col p-4`}><div className="flex items-center justify-between px-2 py-2"><Brand inverse/><button className="lg:hidden p-2" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div><nav className="mt-8 space-y-1" aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);setMobile(false)}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium ${view===id?'bg-[oklch(0.31_0.045_294)] text-white':'text-[oklch(0.76_0.02_294)] hover:bg-[oklch(0.25_0.03_294)] hover:text-white'}`}><Icon size={18}/>{label}{view===id&&<ChevronRight size={15} className="ml-auto"/>}</button>)}</nav><div className="mt-auto border-t border-[oklch(0.34_0.025_294)] pt-4"><button onClick={onLogout} className="w-full flex items-center gap-3 px-3 py-2 text-sm text-[oklch(0.76_0.02_294)] hover:text-white"><DoorOpen size={18}/>Sign out</button></div></aside>
    <main className="flex-1 min-w-0"><header className="h-16 bg-white border-b border-[var(--line)] flex items-center px-4 md:px-6 gap-4 sticky top-0 z-20"><button className="lg:hidden p-1" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="font-semibold capitalize">{nav.find(n=>n[0]===view)?.[1]}</div><div className="ml-auto flex items-center gap-3"><label className="sr-only" htmlFor="environment">Environment</label><select id="environment" className="field py-2 w-auto font-semibold text-xs" value={env} onChange={e=>setEnv(e.target.value as Env|'ALL')}><option value="ALL">All environments</option><option value="DEV">DEV only</option><option value="PROD">PROD only</option></select><button className="btn btn-secondary hidden sm:inline-flex" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh</button></div></header>
      <div className="p-4 md:p-7 max-w-[1440px] mx-auto">{error&&<Notice>{error}</Notice>}{view==='overview'&&<Overview apps={filter(apps)} providers={filter(providers)} credentials={filter(credentials)} grants={filter(grants)} audits={audits} loading={loading}/>} {view==='applications'&&<Applications rows={filter(apps)} loading={loading} reload={load}/>} {view==='providers'&&<Providers rows={filter(providers)} loading={loading} reload={load}/>} {view==='credentials'&&<Credentials rows={filter(credentials)} providers={providers} loading={loading} reload={load}/>} {view==='grants'&&<Grants rows={filter(grants)} apps={apps} providers={providers} credentials={credentials} loading={loading} reload={load}/>} {view==='audit'&&<AuditLog rows={audits} loading={loading}/>}</div>
    </main>
  </div>
}

function Brand({inverse=false}:{inverse?:boolean}){return <div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-[var(--primary)] text-white grid place-items-center"><KeyRound size={17}/></div><span className={`font-semibold tracking-[-.02em] ${inverse?'text-white':'text-[var(--ink)]'}`}>Janus</span></div>}
function Notice({children}:{children:ReactNode}){return <div role="alert" className="mb-5 flex items-center gap-2 p-3 rounded-lg bg-[oklch(0.96_0.025_25)] text-[var(--danger)] text-sm"><CircleAlert size={18}/>{children}</div>}
function EnvBadge({env}:{env:Env}){return <span className={`inline-flex items-center rounded-full px-2 py-1 text-[11px] font-bold ${env==='PROD'?'bg-[oklch(0.93_0.04_25)] text-[oklch(0.4_0.15_25)]':'bg-[oklch(0.93_0.035_235)] text-[oklch(0.38_0.11_235)]'}`}>{env}</span>}
function State({enabled}:{enabled:boolean}){return <span className="inline-flex items-center gap-1.5 text-xs font-medium"><span className={`w-2 h-2 rounded-full ${enabled?'bg-[var(--success)]':'bg-[var(--muted)]'}`}/>{enabled?'Active':'Disabled'}</span>}
function PageTitle({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="flex items-start gap-4 justify-between mb-6"><div><h1 className="text-2xl font-semibold tracking-[-.025em] text-balance">{title}</h1><p className="text-sm text-[var(--muted)] mt-1 max-w-[70ch]">{description}</p></div>{action}</div>}
function Empty({icon:Icon,label}:{icon:typeof Activity;label:string}){return <div className="py-16 text-center"><Icon className="mx-auto text-[var(--muted)]" size={28}/><p className="font-semibold mt-4">{label}</p><p className="text-sm text-[var(--muted)] mt-1">Create the first record to establish this boundary.</p></div>}
function Loading(){return <div className="p-5 space-y-4">{[1,2,3,4].map(i=><div key={i} className="skeleton h-10 rounded-lg"/>)}</div>}
function Table({head,children}:{head:string[];children:ReactNode}){return <div className="panel overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[var(--surface)] text-[var(--muted)] text-left"><tr>{head.map(h=><th key={h} className="px-4 py-3 font-semibold whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y divide-[var(--line)]">{children}</tbody></table></div>}
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-40 bg-[oklch(0.12_0.02_294/.42)] flex justify-end" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label={title} className="h-full w-full max-w-lg bg-white p-6 overflow-y-auto"><div className="flex justify-between items-center"><h2 className="text-xl font-semibold">{title}</h2><button className="btn btn-secondary p-2" onClick={onClose} aria-label="Close"><X size={18}/></button></div><div className="mt-7">{children}</div></section></div>}
function Delete({path,reload}:{path:string;reload:()=>Promise<void>}){const [busy,setBusy]=useState(false);return <button className="btn btn-danger p-2" aria-label="Delete" disabled={busy} onClick={async()=>{if(!confirm('Delete this record? Dependent access may stop immediately.'))return;setBusy(true);try{await api(path,{method:'DELETE'});await reload()}catch(e){alert((e as Error).message)}finally{setBusy(false)}}}><Trash2 size={16}/></button>}

function Overview({apps,providers,credentials,grants,audits,loading}:{apps:Application[];providers:Provider[];credentials:Credential[];grants:Grant[];audits:Audit[];loading:boolean}){const stats=[['Applications',apps.length,AppWindow],['Providers',providers.length,Server],['Credentials',credentials.length,BadgeKey],['Active grants',grants.filter(g=>g.enabled).length,Route]] as const;return <><PageTitle title="Security overview" description="The current shape of application access through this Janus deployment."/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-px bg-[var(--line)] panel overflow-hidden">{stats.map(([l,n,I])=><div className="bg-white p-5" key={l}><div className="flex items-center justify-between text-[var(--muted)]"><span className="text-xs font-semibold">{l}</span><I size={17}/></div><p className="text-3xl font-semibold tabular-nums mt-5">{loading?'—':n}</p></div>)}</div><div className="grid xl:grid-cols-[1.4fr_.6fr] gap-5 mt-6"><div><h2 className="font-semibold mb-3">Recent activity</h2><div className="panel">{loading?<Loading/>:audits.length===0?<Empty icon={Activity} label="No audit activity yet"/>:<div className="divide-y divide-[var(--line)]">{audits.slice(0,6).map(a=><div key={a.id} className="p-4 flex items-center gap-3"><span className={`w-2 h-2 rounded-full ${a.outcome==='SUCCESS'?'bg-[var(--success)]':a.outcome==='DENIED'?'bg-[var(--warning)]':'bg-[var(--danger)]'}`}/><div className="min-w-0"><p className="text-sm font-medium truncate">{a.action.replaceAll('_',' ')}</p><p className="text-xs text-[var(--muted)] mt-1">{new Date(a.occurredAt).toLocaleString()} · {a.actorType}</p></div><span className="ml-auto text-xs font-semibold">{a.statusCode||a.outcome}</span></div>)}</div>}</div></div><div><h2 className="font-semibold mb-3">Trust boundary</h2><div className="panel p-5"><div className="flex flex-col gap-3 text-sm"><Flow icon={AppWindow} text="Application authenticates"/><Flow icon={ShieldCheck} text="Grant and route policy authorize"/><Flow icon={BadgeKey} text="OpenBao supplies credential"/><Flow icon={Boxes} text="Janus calls fixed provider"/></div><p className="text-xs text-[var(--muted)] leading-5 mt-5 pt-4 border-t border-[var(--line)]">Secrets are never returned by the administration or gateway APIs.</p></div></div></div></>}
function Flow({icon:Icon,text}:{icon:typeof Activity;text:string}){return <div className="flex items-center gap-3"><span className="w-8 h-8 rounded-lg bg-[var(--surface)] grid place-items-center text-[var(--primary)]"><Icon size={16}/></span>{text}</div>}

function Applications({rows,loading,reload}:{rows:Application[];loading:boolean;reload:()=>Promise<void>}){const [open,setOpen]=useState(false),[issued,setIssued]=useState<{id:string;key:string}|null>(null);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await api<{application:Application;apiKey:string}>('/applications',{method:'POST',body:JSON.stringify({name:f.get('name'),description:f.get('description'),environment:f.get('environment'),enabled:true})});setIssued({id:r.application.id,key:r.apiKey});await reload()}catch(x){alert((x as Error).message)}}return <><PageTitle title="Applications" description="Machine identities allowed to approach the gateway. API keys are shown once and stored only as hashes." action={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/>New application</button>}/>{loading?<Loading/>:rows.length===0?<Empty icon={AppWindow} label="No applications configured"/>:<Table head={['Application','Environment','Status','Created','']} >{rows.map(r=><tr key={r.id}><td className="px-4 py-3"><p className="font-semibold">{r.name}</p><p className="text-xs text-[var(--muted)] mt-1">{r.description||r.id}</p></td><td className="px-4 py-3"><EnvBadge env={r.environment}/></td><td className="px-4 py-3"><State enabled={r.enabled}/></td><td className="px-4 py-3 text-[var(--muted)] whitespace-nowrap">{new Date(r.createdAt).toLocaleDateString()}</td><td className="px-4 py-3 text-right"><Delete path={`/applications/${r.id}`} reload={reload}/></td></tr>)}</Table>}{open&&<Drawer title="Register application" onClose={()=>setOpen(false)}><form onSubmit={create} className="space-y-5"><Field label="Name" name="name" required/><Field label="Description" name="description"/><Select label="Environment" name="environment" options={['DEV','PROD']}/><Submit label="Create application"/></form></Drawer>}{issued&&<SecretReveal title="Application key issued" value={issued.key} onClose={()=>{setIssued(null);setOpen(false)}}/>}</>}

function Providers({rows,loading,reload}:{rows:Provider[];loading:boolean;reload:()=>Promise<void>}){const [open,setOpen]=useState(false);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/providers',{method:'POST',body:JSON.stringify({name:f.get('name'),slug:f.get('slug'),baseUrl:f.get('baseUrl'),environment:f.get('environment'),enabled:true})});setOpen(false);await reload()}catch(x){alert((x as Error).message)}}return <><PageTitle title="Providers" description="Fixed upstream destinations. Janus resolves and validates each host; gateway callers never supply a URL." action={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/>New provider</button>}/>{loading?<Loading/>:rows.length===0?<Empty icon={Server} label="No providers registered"/>:<Table head={['Provider','Destination','Environment','Status','']} >{rows.map(r=><tr key={r.id}><td className="px-4 py-3"><p className="font-semibold">{r.name}</p><code className="text-xs text-[var(--muted)]">{r.slug}</code></td><td className="px-4 py-3 text-xs max-w-sm truncate">{r.baseUrl}</td><td className="px-4 py-3"><EnvBadge env={r.environment}/></td><td className="px-4 py-3"><State enabled={r.enabled}/></td><td className="px-4 py-3"><Delete path={`/providers/${r.id}`} reload={reload}/></td></tr>)}</Table>}{open&&<Drawer title="Register provider" onClose={()=>setOpen(false)}><form onSubmit={create} className="space-y-5"><Field label="Display name" name="name" required/><Field label="Gateway slug" name="slug" placeholder="example-api" required/><Field label="HTTPS base URL" name="baseUrl" type="url" placeholder="https://api.example.com" required/><Select label="Environment" name="environment" options={['DEV','PROD']}/><Submit label="Create provider"/></form></Drawer>}</>}

function Credentials({rows,providers,loading,reload}:{rows:Credential[];providers:Provider[];loading:boolean;reload:()=>Promise<void>}){const [open,setOpen]=useState(false),[kind,setKind]=useState('BEARER');async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/credentials',{method:'POST',body:JSON.stringify({name:f.get('name'),providerId:f.get('providerId'),environment:f.get('environment'),authType:f.get('authType'),headerName:f.get('headerName')||null,secret:f.get('secret'),enabled:true})});setOpen(false);await reload()}catch(x){alert((x as Error).message)}}return <><PageTitle title="Credentials" description="Metadata lives here; secret values are written directly to OpenBao and cannot be read back through this console." action={<button className="btn btn-primary" onClick={()=>setOpen(true)} disabled={!providers.length}><Plus size={16}/>New credential</button>}/>{loading?<Loading/>:rows.length===0?<Empty icon={BadgeKey} label="No credential references"/>:<Table head={['Credential','Provider','Authentication','Environment','Status','']} >{rows.map(r=><tr key={r.id}><td className="px-4 py-3"><p className="font-semibold">{r.name}</p><p className="text-xs text-[var(--muted)] mt-1">Secret held in OpenBao</p></td><td className="px-4 py-3">{r.providerName}</td><td className="px-4 py-3 text-xs">{r.authType.replaceAll('_',' ')}</td><td className="px-4 py-3"><EnvBadge env={r.environment}/></td><td className="px-4 py-3"><State enabled={r.enabled}/></td><td className="px-4 py-3"><Delete path={`/credentials/${r.id}`} reload={reload}/></td></tr>)}</Table>}{open&&<Drawer title="Add credential" onClose={()=>setOpen(false)}><form onSubmit={create} className="space-y-5"><Field label="Reference name" name="name" required/><Select label="Provider" name="providerId" options={providers.map(p=>({value:p.id,label:`${p.name} · ${p.environment}`}))}/><Select label="Environment" name="environment" options={['DEV','PROD']}/><Select label="Authentication strategy" name="authType" value={kind} onChange={setKind} options={['BEARER','API_KEY_HEADER','BASIC']}/>{kind==='API_KEY_HEADER'&&<Field label="Header name" name="headerName" placeholder="X-Api-Key" required/>}<Field label={kind==='BASIC'?'Username and password (username:password)':'Secret value'} name="secret" type="password" required/><p className="text-xs text-[var(--muted)] leading-5">This value is sent to OpenBao over the internal service connection. Janus stores only its generated reference.</p><Submit label="Store credential"/></form></Drawer>}</>}

function Grants({rows,apps,providers,credentials,loading,reload}:{rows:Grant[];apps:Application[];providers:Provider[];credentials:Credential[];loading:boolean;reload:()=>Promise<void>}){const [open,setOpen]=useState(false);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/grants',{method:'POST',body:JSON.stringify({applicationId:f.get('applicationId'),providerId:f.get('providerId'),credentialId:f.get('credentialId'),environment:f.get('environment'),enabled:true,policies:[{method:f.get('method'),pathPattern:f.get('pathPattern')}]})});setOpen(false);await reload()}catch(x){alert((x as Error).message)}}return <><PageTitle title="Access grants" description="Bind one application to one provider credential, then state exactly which methods and routes it may use." action={<button className="btn btn-primary" onClick={()=>setOpen(true)} disabled={!apps.length||!providers.length||!credentials.length}><Plus size={16}/>New grant</button>}/>{loading?<Loading/>:rows.length===0?<Empty icon={Route} label="No access grants"/>:<div className="space-y-3">{rows.map(r=><div className="panel p-4 flex flex-col lg:flex-row lg:items-center gap-4" key={r.id}><div className="flex items-center gap-3 min-w-0"><span className="w-9 h-9 rounded-lg bg-[var(--surface)] grid place-items-center text-[var(--primary)]"><Route size={17}/></span><div><p className="font-semibold text-sm">{r.applicationName} <span className="text-[var(--muted)] font-normal">→</span> {r.providerName}</p><p className="text-xs text-[var(--muted)] mt-1">Uses {r.credentialName}</p></div></div><div className="flex flex-wrap gap-1.5 lg:ml-auto">{r.policies.map(p=><code key={`${p.method}${p.pathPattern}`} className="text-[11px] bg-[var(--surface)] px-2 py-1 rounded-md"><strong>{p.method}</strong> {p.pathPattern}</code>)}</div><EnvBadge env={r.environment}/><Delete path={`/grants/${r.id}`} reload={reload}/></div>)}</div>}{open&&<Drawer title="Create access grant" onClose={()=>setOpen(false)}><form onSubmit={create} className="space-y-5"><Select label="Application" name="applicationId" options={apps.map(x=>({value:x.id,label:`${x.name} · ${x.environment}`}))}/><Select label="Provider" name="providerId" options={providers.map(x=>({value:x.id,label:`${x.name} · ${x.environment}`}))}/><Select label="Credential" name="credentialId" options={credentials.map(x=>({value:x.id,label:`${x.name} · ${x.environment}`}))}/><Select label="Environment" name="environment" options={['DEV','PROD']}/><div className="grid grid-cols-[120px_1fr] gap-3"><Select label="Method" name="method" options={['GET','POST','PUT','PATCH','DELETE','HEAD']}/><Field label="Allowed path" name="pathPattern" placeholder="/v1/resources/**" required/></div><p className="text-xs text-[var(--muted)] leading-5">Use explicit prefixes. <code>/**</code> is supported but grants access to every route on this provider.</p><Submit label="Create grant"/></form></Drawer>}</>}

function AuditLog({rows,loading}:{rows:Audit[];loading:boolean}){return <><PageTitle title="Audit log" description="Administrative and gateway decisions, ordered newest first. Correlation IDs connect Janus events to upstream traces."/>{loading?<Loading/>:rows.length===0?<Empty icon={ShieldCheck} label="No audit events"/>:<Table head={['Time','Action','Actor','Outcome','Request','Correlation']} >{rows.map(r=><tr key={r.id}><td className="px-4 py-3 text-xs whitespace-nowrap">{new Date(r.occurredAt).toLocaleString()}</td><td className="px-4 py-3 font-medium">{r.action.replaceAll('_',' ')}</td><td className="px-4 py-3 text-xs">{r.actorType}</td><td className="px-4 py-3"><span className={`text-xs font-bold ${r.outcome==='SUCCESS'?'text-[var(--success)]':r.outcome==='DENIED'?'text-[var(--warning)]':'text-[var(--danger)]'}`}>{r.outcome}</span></td><td className="px-4 py-3 text-xs"><strong>{r.requestMethod}</strong> {r.requestPath}</td><td className="px-4 py-3"><code className="text-[11px]">{r.correlationId.slice(0,13)}…</code></td></tr>)}</Table>}</>}

function Field({label,name,type='text',placeholder,required=false}:{label:string;name:string;type?:string;placeholder?:string;required?:boolean}){return <label><span className="label">{label}</span><input className="field" name={name} type={type} placeholder={placeholder} required={required}/></label>}
type Opt=string|{value:string;label:string};
function Select({label,name,options,value,onChange}:{label:string;name:string;options:Opt[];value?:string;onChange?:(v:string)=>void}){return <label><span className="label">{label}</span><select className="field" name={name} value={value} onChange={e=>onChange?.(e.target.value)}>{options.map(o=>{const v=typeof o==='string'?o:o.value,l=typeof o==='string'?o.replaceAll('_',' '):o.label;return <option value={v} key={v}>{l}</option>})}</select></label>}
function Submit({label}:{label:string}){return <button className="btn btn-primary w-full" type="submit">{label}<ArrowRight size={16}/></button>}
function SecretReveal({title,value,onClose}:{title:string;value:string;onClose:()=>void}){const [copied,setCopied]=useState(false);return <div className="fixed inset-0 z-50 bg-[oklch(0.12_0.02_294/.55)] grid place-items-center p-4"><section role="alertdialog" aria-modal="true" className="bg-white rounded-xl p-6 w-full max-w-lg"><span className="w-10 h-10 rounded-lg bg-[oklch(0.92_0.04_155)] text-[var(--success)] grid place-items-center"><Check/></span><h2 className="text-xl font-semibold mt-5">{title}</h2><p className="text-sm text-[var(--muted)] mt-2 leading-6">Copy this key now. Janus stores only its one-way hash and cannot show it again.</p><div className="mt-5 flex gap-2"><code className="field overflow-x-auto whitespace-nowrap">{value}</code><button className="btn btn-secondary" onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true)}}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><button className="btn btn-primary w-full mt-5" onClick={onClose}>I saved the key</button></section></div>}
